### PR TITLE
[beringei] Bump FB_VERSION to 2017.05.22.00

### PR DESCRIPTION
**Pull request by scottfranklin**
Summary:
Update dependencies to be a month newer.

This also forces .thrift files to be recompiled when the thrift
libraries are updated, avoiding mismatches between old generated
thrift files and new thrift common libraries after pulling in new
dependencies with `setup_ubuntu.sh`.

Test Plan: CircleCI

### CODE REVIEW

**Review by mlgood — APPROVED** [review]
Looks like CircleCI passed.  Thanks for doing this!

**Comment by kiranisaac** [comment]
In this new version, if the .thrift files are updated will it automatically build them?

**Review by linuxfood — APPROVED** [review]
Looks good.

**Comment by scottfranklin** [comment]
@kiranisaac it used to re-generate them on every build, but #43 made it do so only when the .thrift files changed.
This ensures it also re-generates the .thrift files whenever fbthrift itself is updated.

**Pull request closed without merging**
